const resources = {
    TR: {
      translation: {
        "Avantajlar": "Avantajlar",
        "Yazılımlarımız": "Yazılımlarımız",
        "Paketler": "Paketler",
        "Özellikler": "Özellikler",
        "Hakkımızda": "Hakkımızda",
        "İletişim": "İletişim",
        "Giriş Yap": "Giriş Yap",
        "Şimdi Dene": "Şimdi Dene",
        "7 GÜN ÜCRETSİZ DENE": "7 GÜN ÜCRETSİZ DENE",
        "English": "İngilizce",
        "Türkçe": "Türkçe",
        "prof":"Profesyonel",
        "cozum":"Çözümleri",
        "aws":"Amazon",
        "hero-desc": "Amazon ve e-ticaret dünyasında başarıya ulaşmanız için en kolay ve hızlı yol MoonAmz ile başlar.",
        "partnership-desc": "MoonAmz, 20'den fazla ülkede resmi Amazon partneri olarak güvenli ve hızlı e-ticaret deneyimi sunar. Tüm süreçlerde yanınızdayız.",
        "partnership-title": "20 Farklı Ülkede Resmi Amazon Partneri MoonAmz ile Satış Yap!",
        "partnership-feature-1": "Müşteri Memnuniyeti",
        "partnership-feature-2": "Güvenli e-ticaret",
        "benefits-left-1": "Müşteri memnuniyetini ön planda tutan destek",
        "benefits-left-2": "Her adımda şeffaf ve güvenilir hizmet",
        "benefits-left-3": "Satış sonrası sürekli iletişim",
        "benefits-left-4": "Kişiye özel çözüm ve danışmanlık",
        "benefits-right-1": "Amazon süreçlerinde tam güvenlik",
        "benefits-right-2": "Veri gizliliği ve hızlı teslimat",
        "benefits-right-3": "Uzman ekiple 7/24 destek",
        "benefits-right-4": "Yasal ve güncel altyapı",
        "expert-desc": "MoonAmz ekibi, e-ticaret yolculuğunuzda size uzman rehberlik ve pratik çözümler sunar. Her adımda yanınızdayız.",
        "warehouse-desc": "Ara depo hizmetimizle ürünlerinizi güvenle saklayın, hızlı ve sorunsuz teslimat avantajı yaşayın.",
        "blog-excerpt-1": "Amazon'un temellerini öğrenin ve ilk satışınızı hızla yapın.",
        "blog-excerpt-2": "Satış süreçlerinizi optimize edin, başarıya ulaşın.",
        "blog-excerpt-3": "Müşteri memnuniyetini artırmanın yollarını keşfedin.",
        "footer-desc": "MoonAmz ile e-ticaret dünyasında fark yaratın. Güvenli, hızlı ve yenilikçi çözümler için buradayız.",
        "maintenance-title": "Bilgilendirme",
        "maintenance-desc": "Size daha iyi hizmet verebilmek için değişiklikler yapıyoruz. Süreç tamamlandığında sizi bilgilendireceğiz.",
        "contact-send": "Gönder",
        "contact-name-placeholder": "Adınız Soyadınız",
        "contact-email-placeholder": "E-posta Adresiniz",
        "contact-phone-placeholder": "Telefon Numaranız",
        "contact-message-placeholder": "Mesajınız",
        "contact-success": "Mesajınız alındı! En kısa sürede size dönüş yapacağız.",
        "features-title-1": "Yazılıma Kayıt Ol",
        "features-desc-1": "Hızlı ve kolay kayıt işlemiyle hemen başlayın.",
        "features-title-2": "Strateji Belirle",
        "features-desc-2": "Başarılı satış için stratejinizi oluşturun.",
        "features-title-3": "Satış Yap",
        "features-desc-3": "Ürünlerinizi kolayca satışa sunun ve yönetin.",
        "features-title-4": "Ek Gelir Kazan",
        "features-desc-4": "Fazla vakit harcamadan ek gelir elde edin.",
        "benefits-title-1": "Müşteri Memnuniyeti",
        "benefits-title-2": "Güvenli e-ticaret",
        "contact-title-1": "İletişime Geç",
        "contact-title-2": "Hemen Kazanmaya Başla!",
        "statistics-title": "Başarılarımız",
        "statistics-label-1": "Yıllık Deneyim",
        "statistics-label-2": "Mutlu Kullanıcı",
        "statistics-label-3": "Ödeme Alan",
        "expert-title": "MoonAmz ile Uzman Rehberlikte Tanışın",
        "expert-desc": "MoonAmz ekibi, e-ticaret yolculuğunuzda size uzman rehberlik ve pratik çözümler sunar. Her adımda yanınızdayız.",
        "expert-button": "Uzman Gönder",
        "pricing-title": "Paketlerimiz",
        "pricing-package-1": "Temel Paket",
        "pricing-package-2": "Standart Paket",
        "pricing-package-3": "Premium Paket",
        "pricing-feature-1": "Sürekli A/B Test Desteği Sistemi",
        "pricing-feature-2": "Tüm Özellikleri Proje Raporları",
        "pricing-feature-3": "Dünyanın Süreci Raporları",
        "pricing-feature-4": "Üretim Ayrıntıları",
        "pricing-feature-5": "Sürekli FTB Dökümler Sistemi",
        "pricing-feature-6": "Temel Güvenli e-ticaret",
        "pricing-feature-7": "Yerel Danışmanlık Doku Faaliyetleri",
        "pricing-feature-8": "Sürekli Güvenli e-ticaret",
        "pricing-period": "Ay",
        "pricing-select": "PAKETİ SEÇ",
        "support-title-1": "İhtiyacın Olan Tüm Ayrıntılar",
        "support-title-2": "Tek Çatı Altında",
        "support-type-1": "YAZILIM",
        "support-desc-1": "Yazılım ve teknik destek alanında uzman ekibimiz 7/24 hizmetinizdedir. Tüm sorularınız için buradayız.",
        "support-type-2": "ARA DEPO",
        "support-desc-2": "e-ticaret süreçlerinizde ara depo hizmetleri ile güvenli ve hızlı teslimat sağlayın.",
        "support-type-3": "DESTEK",
        "support-desc-3": "Müşteri hizmetleri ve satış sonrası destek ile her zaman yanınızdayız. Sorularınız için iletişime geçin.",
        "warehouse-title-1": "MoonAMZ Ara Depo",
        "warehouse-title-2": "Güvenli - Hızlı - Pratik",
        "warehouse-desc": "Ara depo hizmetimizle ürünlerinizi güvenle saklayın, hızlı ve sorunsuz teslimat avantajı yaşayın.",
        "blog-title-main-1": "Kısa Bir Mola!",
        "blog-title-main-2": "MoonAmz",
        "blog-title-main-3": "Blog",
        "blog-title-1": "Amazon e-ticaret'in Temellerini Yakalayan",
        "blog-title-2": "En Büyük Satış Süreçleri ile Durumu Değiştitebilirsin...",
        "blog-title-3": "Amazon e-ticaret Müşteri Değiştirmelerin Önemi: Başarının Oral Açıkları",
        "blog-category-1": "Başlangıç",
        "blog-category-2": "Pazarlama",
        "blog-category-3": "Müşteri Hizmetleri",
        "blog-date-1": "15 Haziran 2024",
        "blog-date-2": "10 Haziran 2024",
        "blog-date-3": "5 Haziran 2024",
        "blog-read-more": "Devamını Oku →",
        "footer-menu-title": "Menü",
        "footer-quick-title": "Hızlı Erişim",
        "footer-legal-1": "E-ticaret Yasal Hizmet Şartları",
        "footer-legal-2": "Gizlilik Politikası",
        "footer-legal-3": "Çerez Politikası",
        "footer-legal-4": "Yasal Uyarı",
        "footer-legal-5": "Mesafeli Satış Sözleşmesi",
        "footer-phone": "+90 535 363 83 68",
        "footer-email": "info@moonamz.com",
        "footer-address": "İstanbul, Türkiye",
        "footer-copyright": "© 2024 MoonAmz. Tüm hakları saklıdır.",
        "hero-title": "Profesyonel",
        "hero-aws": "Amazon",
        "hero-solution": "Çözümleri",
        "hero-description": "Amazon ve e-ticaret dünyasında başarıya ulaşmanız için en kolay ve hızlı yol MoonAmz ile başlar.",
        "hero-free-trial": "7 GÜN ÜCRETSİZ DENE",
        "testimonials-title": "Üstün Müşteri Memnuniyeti",
        "testimonials-name-1": "Murat Ö.",
        "testimonials-role-1": "Satıcı",
        "testimonials-text-1": "MoonAmz ile çalışmaya başladıktan sonra satışlarım 3 katına çıktı. Profesyonel destek ve güvenilir sistem sayesinde işimi büyüttüm. Herkese tavsiye ederim çünkü gerçekten işe yarıyor.",
        "testimonials-name-2": "Ayşe S.",
        "testimonials-role-2": "E-ticaret Uzmanı",
        "testimonials-text-2": "Amazon e-ticaret konusunda hiç deneyimim yoktu. MoonAmz ekibi bana her adımda yardımcı oldu. Şimdi ayda düzenli gelir elde ediyorum ve çok memnunum. Teşekkürler MoonAmz!",
        "testimonials-name-3": "Buğra A.",
        "testimonials-role-3": "Yeni Başlayan",
        "testimonials-text-3": "Başlangıçta çok tedirgin oldum açıkçası. Ama MoonAmz'nin verdiği eğitim ve destek sayesinde kısa sürede başarılı olmaya başladım. Yazılım çok kullanışlı ve anlaşılır.",
      }
    },
    EN: {
      translation: {
        "Avantajlar": "Advantages",
        "Yazılımlarımız": "Our Software",
        "Paketler": "Packages",
        "Özellikler": "Features",
        "Hakkımızda": "About Us",
        "İletişim": "Contact",
        "Giriş Yap": "Login",
        "Şimdi Dene": "Try Now",
        "7 GÜN ÜCRETSİZ DENE": "TRY 7 DAYS FREE",
        "English": "English",
        "Türkçe": "Turkish",
        "prof":"Professional",
        "cozum":"Solutions",
        "aws":"Amazon",
        "hero-desc": "The easiest and fastest way to succeed in Amazon and e-commerce starts with MoonAmz.",
        "partnership-desc": "MoonAmz offers a secure and fast e-commerce experience as an official Amazon partner in over 20 countries. We are with you at every step.",
        "partnership-title": "Sell with MoonAmz, the Official Amazon Partner in 20+ Countries!",
        "partnership-feature-1": "Customer Satisfaction",
        "partnership-feature-2": "Secure e-commerce",
        "benefits-left-1": "Support focused on customer satisfaction",
        "benefits-left-2": "Transparent and reliable service at every step",
        "benefits-left-3": "Continuous communication after sales",
        "benefits-left-4": "Personalized solutions and consultancy",
        "benefits-right-1": "Full security in Amazon processes",
        "benefits-right-2": "Data privacy and fast delivery",
        "benefits-right-3": "24/7 support with expert team",
        "benefits-right-4": "Legal and up-to-date infrastructure",
        "expert-desc": "The MoonAmz team offers expert guidance and practical solutions on your e-commerce journey. We are with you every step of the way.",
        "warehouse-desc": "Store your products safely with our warehouse service and enjoy fast, seamless delivery.",
        "blog-excerpt-1": "Learn the basics of Amazon and make your first sale quickly.",
        "blog-excerpt-2": "Optimize your sales processes and achieve success.",
        "blog-excerpt-3": "Discover ways to increase customer satisfaction.",
        "footer-desc": "Make a difference in e-commerce with MoonAmz. We are here for secure, fast, and innovative solutions.",
        "maintenance-title": "Notice",
        "maintenance-desc": "We are making improvements to serve you better. We will notify you when the process is complete.",
        "contact-send": "Send",
        "contact-name-placeholder": "Your Name",
        "contact-email-placeholder": "Your Email Address",
        "contact-phone-placeholder": "Your Phone Number",
        "contact-message-placeholder": "Your Message",
        "contact-success": "Your message has been received! We will get back to you as soon as possible.",
        "features-title-1": "Register to the Platform",
        "features-desc-1": "Start right away with a fast and easy registration process.",
        "features-title-2": "Set Your Strategy",
        "features-desc-2": "Create your strategy for successful sales.",
        "features-title-3": "Make Sales",
        "features-desc-3": "Easily list and manage your products for sale.",
        "features-title-4": "Earn Extra Income",
        "features-desc-4": "Earn extra income without spending much time.",
        "benefits-title-1": "Customer Satisfaction",
        "benefits-title-2": "Secure e-commerce",
        "contact-title-1": "Get in Touch",
        "contact-title-2": "Start Winning Now!",
        "statistics-title": "Our Achievements",
        "statistics-label-1": "Years of Experience",
        "statistics-label-2": "Happy Users",
        "statistics-label-3": "Paid Users",
        "expert-title": "Meet Expert Guidance with MoonAmz",
        "expert-desc": "The MoonAmz team offers expert guidance and practical solutions on your e-commerce journey. We are with you every step of the way.",
        "expert-button": "Send Expert",
        "pricing-title": "Our Packages",
        "pricing-package-1": "Basic Package",
        "pricing-package-2": "Standard Package",
        "pricing-package-3": "Premium Package",
        "pricing-feature-1": "Continuous A/B Test Support System",
        "pricing-feature-2": "All Features Project Reports",
        "pricing-feature-3": "Global Process Reports",
        "pricing-feature-4": "Production Details",
        "pricing-feature-5": "Continuous FTB Documentation System",
        "pricing-feature-6": "Basic Secure e-commerce",
        "pricing-feature-7": "Local Consultancy Activities",
        "pricing-feature-8": "Continuous Secure e-commerce",
        "pricing-period": "Month",
        "pricing-select": "SELECT PACKAGE",
        "support-title-1": "All the Details You Need",
        "support-title-2": "Under One Roof",
        "support-type-1": "SOFTWARE",
        "support-desc-1": "Our expert team in software and technical support is at your service 24/7. We are here for all your questions.",
        "support-type-2": "WAREHOUSE",
        "support-desc-2": "Ensure safe and fast delivery with warehouse services in your e-commerce processes.",
        "support-type-3": "SUPPORT",
        "support-desc-3": "We are always with you with customer service and after-sales support. Contact us for your questions.",
        "warehouse-title-1": "MoonAMZ Warehouse",
        "warehouse-title-2": "Secure - Fast - Practical",
        "warehouse-desc": "Store your products safely with our warehouse service and enjoy fast, seamless delivery.",
        "blog-title-main-1": "Take a Short Break!",
        "blog-title-main-2": "MoonAmz",
        "blog-title-main-3": "Blog",
        "blog-title-1": "Mastering the Basics of Amazon e-commerce",
        "blog-title-2": "Change the Game with the Biggest Sales Processes...",
        "blog-title-3": "The Importance of Customer Changes in Amazon e-commerce: Secrets of Success",
        "blog-category-1": "Getting Started",
        "blog-category-2": "Marketing",
        "blog-category-3": "Customer Service",
        "blog-date-1": "June 15, 2024",
        "blog-date-2": "June 10, 2024",
        "blog-date-3": "June 5, 2024",
        "blog-read-more": "Read More →",
        "footer-menu-title": "Menu",
        "footer-quick-title": "Quick Access",
        "footer-legal-1": "e-commerce Legal Terms of Service",
        "footer-legal-2": "Privacy Policy",
        "footer-legal-3": "Cookie Policy",
        "footer-legal-4": "Legal Notice",
        "footer-legal-5": "Distance Sales Agreement",
        "footer-phone": "+90 535 363 83 68",
        "footer-email": "info@moonamz.com",
        "footer-address": "Istanbul, Turkey",
        "footer-copyright": "© 2024 MoonAmz. All rights reserved.",
        "hero-title": "Professional",
        "hero-aws": "Amazon",
        "hero-solution": "Solutions",
        "hero-description": "The easiest and fastest way to succeed in Amazon and e-commerce starts with MoonAmz.",
        "hero-free-trial": "TRY 7 DAYS FREE",
        "testimonials-title": "Outstanding Customer Satisfaction",
        "testimonials-name-1": "Murat O.",
        "testimonials-role-1": "Seller",
        "testimonials-text-1": "After I started working with MoonAmz, my sales tripled. I grew my business thanks to professional support and a reliable system. I recommend it to everyone because it really works.",
        "testimonials-name-2": "Ayşe S.",
        "testimonials-role-2": "E-commerce Specialist",
        "testimonials-text-2": "I had no experience in Amazon e-commerce. The MoonAmz team helped me at every step. Now I earn regular income every month and I am very satisfied. Thank you MoonAmz!",
        "testimonials-name-3": "Bugra A.",
        "testimonials-role-3": "Beginner",
        "testimonials-text-3": "Honestly, I was very hesitant at first. But thanks to the training and support from MoonAmz, I started to succeed in a short time. The software is very useful and easy to understand.",
      }
    }
  };

  export default resources;